### ISSUE TITLE
unnecessary for-loop

### ISSUE THREAD

**Issue by Kai-46** [bmild/nerf#11]
Thanks for sharing the code. 

The for-loop in run_nerf_helpers.py ([line 104-105](https://github.com/bmild/nerf/blob/f483d7340d8de2b81348ba8f720cfb62425dbdb1/run_nerf_helpers.py#L104) ) does not seem to be necessary. Could this be a bug?

**Comment by bmild** [comment]
Good catch. I've just pushed a commit with the for loop hardcoded to 1 (so it's easy to add hidden layers if desired). 

Note: the supplement to the paper mistakenly states that there are 4 hidden layers here rather than 1. Since this is how all the experiments were run, we're making the architecture from the code canonical rather than the paper.
