### ISSUE TITLE
physical intuition behind ndc_rays?

### ISSUE THREAD

**Issue by Kai-46** [bmild/nerf#18]
Thanks for sharing the great work! I noticed that in the codebase, there's special handling of forward-facing data, specifically, [this ndc_rays function](https://github.com/bmild/nerf/blob/cf364d90964117a117116ab378ab9fafd04db290/run_nerf_helpers.py#L137). I wonder what is the physical intuition behind it. It's a bit hard for me to digest this piece of code snippet. Any help is appreciated!

**Comment by bmild** [comment]
The general intuition is that NDC is a space where the z axis maps to _inverse_ depth (disparity) rather than depth, which should be a good space for uniformly sampling points along rays when dealing with forward facing scenes (matches the sampling from the input cameras better). NDC is just what you get when you pass points through the OpenGL projection matrix, which is a linear transform in homogeneous space, so it maps rays to rays. However, the transformation is a little subtle since there is a divide by z step.

Here is a pdf I wrote up deriving the equations in `ndc_rays()` we use to convert rays in regular camera space to NDC space: [ndc_derivation.pdf](https://github.com/bmild/nerf/files/4451808/ndc_derivation.pdf)

Here's a [great reference](http://www.songho.ca/opengl/gl_projectionmatrix.html) on the OpenGL projection matrix.

**Comment by Kai-46** [comment]
Thanks a lot for the detailed explanation. If I understand it correctly, the final goal is just to sample points on each physical rays such that the inverse depths (1/z) of these sampled points are evenly spaced inside the interval (0,1/near_plane). As long as this goal is fulfilled, it doesn't make a difference whether one adopts this NDC trick or not, right?

**Comment by bmild** [comment]
Note that we have an argument `linspace` to do linear sampling in disparity along the rays. The reason we use NDC instead of this for the forward facing scenes is that we find it actually negatively impacts the network itself if the input coordinates are very far from having a uniform distribution in space. So with linear disparity sampling, the far points end up being spaced much much farther apart than the near points. Especially with the positional encoding (where far apart points effectively make the higher frequency encodings useless), we find that this "confuses" the network and produces grainy results in the backgrounds. Hence the use of NDC when possible in unbounded scenes.

**Comment by Kai-46** [comment]
I see. Looks like it's important for the coordinates of 3d points sampled along physical rays to uniformly distribute in the cube [-1, 1]^3, so that positional encoding can works properly (btw, my understanding is that the **sin, cos** basis used in positional encoding are fundamental frequencies of this bounded cube; if the size of the bounded cube changes, the fundamental frequencies might also need to adjust accordingly). For unbounded scenes, because the coordinates of the sampled 3d points are not bounded, we need to apply NDC trick to map the unbounded coordinates to be bounded. Thanks again for the clarification!

**Comment by zhshi0816** [comment]
I have one question about your ndc_derivation.pdf. For my understanding, the ndc transformation matrix in your pdf file is used to transform eye coordinate to ndc coordination and your following derivations are all based on that. But according to your code, the inputs for the ndc_rays function are based on world coordinate. Can you explain it a little bit?

**Comment by MobiusLqm** [comment]
> I have one question about your ndc_derivation.pdf. For my understanding, the ndc transformation matrix in your pdf file is used to transform eye coordinate to ndc coordination and your following derivations are all based on that. But according to your code, the inputs for the ndc_rays function are based on world coordinate. Can you explain it a little bit?

Hi，I have the same question. Have you solved this? maybe we can have a disscussion ,  In my oppinion, maybe because Ndc_rays is used in LLFF dataset only , which have a feature that all cameras are forward facing( all most all cams are in the same direction and on the same side of the scene), so it can use only one NDC  space for all diffrent cameras.
