### ISSUE TITLE
some maths about weights sum

### ISSUE THREAD

**Issue by kwea123** [bmild/nerf#28]
I found this part of code confusing at first sight:
https://github.com/bmild/nerf/blob/c39def3944c982aa7aabeacdd2e856c07da39b9e/run_nerf.py#L145-L154

More precisely, you divide by the weights sum for disparity but not for rgb and depth.

**Comment by bmild** [comment]
This is just for visualization, the `disp_map` is what's shown in Tensorboard so it's convenient to divide out the weight sum. Else the visualized disparity map will not look correct in regions that are "partially transparent" where the accumulated opacity is < 1. For RGB we do not want to normalize since it's part of the rendering model that rays do not necessarily have to accumulated full opacity, they can be transparent or partially transparent.
