### ISSUE TITLE
imagemagick in “environment.yml”  &&" log\summaries " folder

### ISSUE THREAD

**Issue by 123Ray321** [bmild/nerf#32]
exception 1：
input： `conda env create -f environment.yml`
This error occurred：ResolvePackageNotFound: - imagemagick
exception 2：
After downloading the data.Run this order `python run_nerf.py --config config_fern.txt` directly. 
This error occurred：
Failed to create a directory: ./logs\summaries\fern_test
by the way,I am using Windows os.
Please answer my simple questions.I would be most grateful

**Comment by 123Ray321** [comment]
` os.path.join(basedir+'/summaries/'+expname))`
I changed this up here, and exception 2 disappeared, but the following exception appeared:
`ResourceExhaustedError: OOM when allocating tensor with shape[4194304,90] `
It won't work at 500:
```
fern_test 200 17.888735 0.03314802 200
iter time 0.32269
fern_test 300 18.281603 0.030729983 300
iter time 0.32434
fern_test 400 18.99517 0.02551112 400
iter time 0.31992
fern_test 500 19.069906 0.025890702 500
iter time 0.32237
```

My laptop's graphics card is 1660tI.6 g memory.Isn't that enough?
Do you have a solution?I would be most grateful.

**Comment by bmild** [comment]
Re. problem 1: it looks imagemagick is not available for Windows through conda. If you end up needing it (it's only used for the LLFF data loader) there are binaries available [here](https://imagemagick.org/script/download.php).

Re. the memory issue: We trained on 16GB GPUs. The arguments you can adjust to decrease memory usage are `--chunk` and `--netchunk`. In particular, try setting `--chunk 4096` since it sounds like the training fits (which is probably 4096 rays) but the rendering step that traces more rays is failing; this should hopefully make the usage the same between train and test.

**Comment by 123Ray321** [comment]
It works.Thanks for your help.
