### ISSUE TITLE
LLFF data preprocessing

### ISSUE THREAD

**Issue by kwea123** [bmild/nerf#34]
From what I can decipher, the `pose_bounds.npy` contains 3x5 pose matrices and 2 depth bounds for each image. Each pose has [R T] as the left 3x4 matrix and [H W F] as the right 3x1 matrix.

However I get confused by the functions `poses_avg` and `recenter_poses`. What do these functions do and why?

I checked the [original code](https://github.com/Fyusion/LLFF/blob/master/llff/poses/pose_utils.py) but there aren't these averaging or recentering.

**Comment by bmild** [comment]
> From what I can decipher, the pose_bounds.npy contains 3x5 pose matrices and 2 depth bounds for each image. Each pose has [R T] as the left 3x4 matrix and [H W F] as the right 3x1 matrix.

This is correct. Another note is that the R matrix is in the form [down right back] instead of [right up back] which is why we must fix it after loading.

> However I get confused by the functions poses_avg and recenter_poses. What do these functions do and why?

`poses_avg` computes a "central" pose for the dataset, based on using the mean translation, the mean z axis, and adopting the mean y axis as an "up" direction (so that Up x Z = X and then Z x X = Y). `recenter_poses` very simply applies the inverse of this average pose to the dataset (a rigid rotation/translation) so that the identity extrinsic matrix is looking at the scene, which is nice because normalizes the orientation of the scene for later rendering from the learned NeRF. This is also important for using NDC coordinates, since we assume the scene is centered there too.

**Comment by kwea123** [comment]
So this pose recentering needs to be applied on real data where the camera poses are arbitrary, is that correct? Leave aside rendering, does it have impact on training: train on llff without `rencenter_poses` and with NDC? Intuitively it depends how how much the default world center differs from the recentered pose, in practice when using COLMAP, do they differ much?

**Comment by bmild** [comment]
NDC makes very specific assumptions, that the camera is facing along -z and is entirely behind the z=-near plane. So if the rotation is wrong it will fail (in its current implementation). This is analogous to how a regular graphics pipeline like OpenGL will apply the world-to-camera to move to camera space (where camera is looking along -z) before converting to NDC coordinates.

In practice the average translation is not too far from the origin but the rotation comes out pretty arbitrary from COLMAP.

This is all specific to the forward facing scenes though. You might notice we have a different `spherify`function for when the cameras are all pointing at some central object of interest, which places this point at the origin and rescales the sphere of cameras so the average distance to the origin is 1. This is another example of a way to transform and scale the input cameras so that they are all in a more predictable space -- what's important in the end is that you have known bounds on the region of the scene you care about (whole scene for forward facing or central object for 360 capture) since this must be scaled right for the positional encoding to make sense.

**Comment by kwea123** [comment]
Thanks, my question about centering the poses is clear now.

> The bounds must be scaled right for the positional encoding to make sense.

I agree with that, so the `bd_factor` is used to make the near plane at distance around 1. How about the far plane? For scene "fern" the bounds are about 1 and 4 after scaled here
https://github.com/bmild/nerf/blob/8edde335d2b18188769850b03c45515352d66b31/load_llff.py#L257-L259
but the near and far planes are always set to 0 and 1:
https://github.com/bmild/nerf/blob/8edde335d2b18188769850b03c45515352d66b31/run_nerf.py#L610-L612

Could you please explain how it works?

**Comment by bmild** [comment]
The NDC code takes in a "near" bound and assumes the far bound is infinity (this doesn't matter too much since NDC space samples in 1/depth so moving from "far" to infinity is only slightly less sample-efficient). You can see here that the "near" bound is hardcoded to 1 in the way we call it in `run_nerf.py`:
https://github.com/bmild/nerf/blob/8edde335d2b18188769850b03c45515352d66b31/run_nerf.py#L312-L313
This is why the loading code is set up to scale a scene so that the nearest bound in `bds` (pushed forward by `bd_factor` in case the bound wasn't conservative enough) is scaled to become 1. Then the assumption matches.

For more details on how we use NDC space see my [PDF writeup](https://github.com/bmild/nerf/files/4451808/ndc_derivation.pdf) posted in [this issue](https://github.com/bmild/nerf/issues/18).

**Comment by kwea123** [comment]
Oh I got it. To make sure I didn't misunderstand, I write it here:
We want to sample the points from -n (n=1 after scaling) to infinity, to do that we first "move o to the ray’s intersection with the near plane at z = -n" and "simply sample t0 linearly from 0 to 1". So the near=0 and far=1 actually correspond to the 0 and 1 in this last quote!
Thanks so much, it's much more clear now.

**Comment by whappily** [comment]
Why do we need 'camera_angle_x' and 'rotation'  ?What is 'camera_angle_x' and 'rotation' in data ?

**Comment by NagabhushanSN95** [comment]
`camera_angle_x` is used to compute focal length. No idea what `rotation` is!

**Comment by Fishermanykx** [comment]
> No idea what rotation is!

I think you can refer to this: https://github.com/fyusion/llff#using-your-own-poses-without-running-colmap, which gives a clear explaination.

**Comment by YZsZY** [comment]
Hi, I still have some confusion about center_pose! I was able to figure out how to get the pose_avg, but I can't understand the operation of this line of code `poses_centered = np.linalg.inv(pose_avg_homo) @ poses_homo  # (N_images, 4, 4)`.
    The pose_avg_homo corresponds to the transformation of **Cam_center2World**, so its inverse corresponds to the the transformation of **World2Cam_center**, and the poses_homo corresponds to Cam2World. 
    But looking at it this way, if we want to get the transformation of **Cam2Cam_center**, the code should be poses_homo @ np.linalg.inv(pose_avg_homo) (**Cam2World X World2Cam_center**). 
    If there is something I got wrong in this, I hope to be able to point out to everyone!

**Comment by ITBoy-China** [comment]
@YZsZY 
I think you misunderstood something. The followings are things which we both argee.

1.`pose_avg_homo` and `poses_homo` are c2w matrix.

2.`poses_centered` means that we make all c2w poses to be describled by average pose. That's to say we use average pose position as origin.

And the followings are things which you misunderstood.

1.You simply regard `w2c @ c2w` as `w2w`. And `np.linalg.inv(pose_avg_homo) @ poses_homo` means if I have a point `A` describled by `poses_homo`. First `poses_homo @ A`  means that we transfer a point from camera to world. And `np.linalg.inv(pose_avg_homo) @ poses_homo @ A` means that we transfer as point from camera to world and to another camera. Because `np.linalg.inv(pose_avg_homo)` is `w2c`.

2.But  `np.linalg.inv(pose_avg_homo)` means that you transfer points describled by world to avg_pose，and `poses_homo` means that you transfer points from camera to world. So if we have a point B describled by world,then `np.linalg.inv(pose_avg_homo) @ B` means that we transfer world to `pose_avg_homo`, but `pose_homo` needs camera points describled by `poses_homo` not `pose_avg_homo`. So `poses_homo @ np.linalg.inv(pose_avg_homo)` makes no sense.

**Comment by YZsZY** [comment]
> @YZsZY I think you misunderstood something. The followings are things which we both argee.
> 
> 1.`pose_avg_homo` and `poses_homo` are c2w matrix.
> 
> 2.`poses_centered` means that we make all c2w poses to be describled by average pose. That's to say we use average pose position as origin.
> 
> And the followings are things which you misunderstood.
> 
> 1.You simply regard `w2c @ c2w` as `w2w`. And `np.linalg.inv(pose_avg_homo) @ poses_homo` means if I have a point `A` describled by `poses_homo`. First `poses_homo @ A` means that we transfer a point from camera to world. And `np.linalg.inv(pose_avg_homo) @ poses_homo @ A` means that we transfer as point from camera to world and to another camera. Because `np.linalg.inv(pose_avg_homo)` is `w2c`.
> 
> 2.But `np.linalg.inv(pose_avg_homo)` means that you transfer points describled by world to avg_pose，and `poses_homo` means that you transfer points from camera to world. So if we have a point B describled by world,then `np.linalg.inv(pose_avg_homo) @ B` means that we transfer world to `pose_avg_homo`, but `pose_homo` needs camera points describled by `poses_homo` not `pose_avg_homo`. So `poses_homo @ np.linalg.inv(pose_avg_homo)` makes no sense.

Sorry, I misunderstood the spatial transformation of the camera pose before,  now I understand it, but still thank you for your enthusiastic answer!

**Comment by chufall** [comment]
> @YZsZY I think you misunderstood something. The followings are things which we both argee.
> 
> 1.`pose_avg_homo` and `poses_homo` are c2w matrix.
> 
> 2.`poses_centered` means that we make all c2w poses to be describled by average pose. That's to say we use average pose position as origin.
> 
> And the followings are things which you misunderstood.
> 
> 1.You simply regard `w2c @ c2w` as `w2w`. And `np.linalg.inv(pose_avg_homo) @ poses_homo` means if I have a point `A` describled by `poses_homo`. First `poses_homo @ A` means that we transfer a point from camera to world. And `np.linalg.inv(pose_avg_homo) @ poses_homo @ A` means that we transfer as point from camera to world and to another camera. Because `np.linalg.inv(pose_avg_homo)` is `w2c`.
> 
> 2.But `np.linalg.inv(pose_avg_homo)` means that you transfer points describled by world to avg_pose，and `poses_homo` means that you transfer points from camera to world. So if we have a point B describled by world,then `np.linalg.inv(pose_avg_homo) @ B` means that we transfer world to `pose_avg_homo`, but `pose_homo` needs camera points describled by `poses_homo` not `pose_avg_homo`. So `poses_homo @ np.linalg.inv(pose_avg_homo)` makes no sense.

Thanks for you clear explaination!
But I have been confused about the result  np.linalg.inv(pose_avg_homo) @ poses_homo is a w2c matrix or c2w matrix.
From your explaination , the result matrix should be a c2c matrix ?  
but in the  code , Why  the " np.linalg.inv(pose_avg_homo) @ poses_homo " is used as c2w matrix ?

If there is something I got wrong in this, I hope to be able to point out to everyone! 
Thanks a lot!

**Comment by charlietianx** [comment]
> @ITBoy-China
> 
> > @YZsZY I think you misunderstood something. The followings are things which we both argee.
> > 1.`pose_avg_homo` and `poses_homo` are c2w matrix.
> > 2.`poses_centered` means that we make all c2w poses to be describled by average pose. That's to say we use average pose position as origin.
> > And the followings are things which you misunderstood.
> > 1.You simply regard `w2c @ c2w` as `w2w`. And `np.linalg.inv(pose_avg_homo) @ poses_homo` means if I have a point `A` describled by `poses_homo`. First `poses_homo @ A` means that we transfer a point from camera to world. And `np.linalg.inv(pose_avg_homo) @ poses_homo @ A` means that we transfer as point from camera to world and to another camera. Because `np.linalg.inv(pose_avg_homo)` is `w2c`.
> > 2.But `np.linalg.inv(pose_avg_homo)` means that you transfer points describled by world to avg_pose，and `poses_homo` means that you transfer points from camera to world. So if we have a point B describled by world,then `np.linalg.inv(pose_avg_homo) @ B` means that we transfer world to `pose_avg_homo`, but `pose_homo` needs camera points describled by `poses_homo` not `pose_avg_homo`. So `poses_homo @ np.linalg.inv(pose_avg_homo)` makes no sense.
> 
> Thanks for you clear explaination! But I have been confused about the result np.linalg.inv(pose_avg_homo) @ poses_homo is a w2c matrix or c2w matrix. From your explaination , the result matrix should be a c2c matrix ? but in the code , Why the " np.linalg.inv(pose_avg_homo) @ poses_homo " is used as c2w matrix ?
> 
> If there is something I got wrong in this, I hope to be able to point out to everyone! Thanks a lot!

I have the same question as you. I'm thinking, maybe this truly is a c2c matrix. Because at the end for calculating NDC rays, we do need camera space coordinates. If it is c2w, then we would be using world coordinate to calculate NDC rays. @bmild said 'This is analogous to how a regular graphics pipeline like OpenGL will apply the world-to-camera to move to camera space (where camera is looking along -z) before converting to NDC coordinates', I wonder he means that this recenter actually finally convert the poses to c2c matrices.

**Comment by 356255531** [comment]
> ```pose_avg_homo``` is indeed a c2w matrix, which maps the points in the camera coordinate (alias ```cx```) corresponding to an average pose to the world coordinate. When it is composed with any other c2w matrix (e.g., ```pose_homo``` with the camera coordinate denoted as ```cy```) in such a way```np.linalg.inv(pose_avg_homo) * pose_homo```, the composition simply means to transform the points in ```cy``` to ```cx```, ```np.linalg.inv(pose_avg_homo) * pose_homo``` is now literally a ```cy2cx``` matrix. Just as the author said, the purpose is to replace the ```w``` with ```cx``` for some nice properties. For instance, the original pose is facing the scene etc.
