### ISSUE TITLE
What can we do with our own trained model?

### ISSUE THREAD

**Issue by SpongeGirl** [bmild/nerf#44]
I've trained my own nerf model using 80~100 real images successfully, it takes 8 hours for 50000 iters (probably my GPU not so good), so i think it will take four times hours for 20k iters, it's too long.

And i have no idea about how to use the trained model, because it's not like most general deep learning models. In my opinion, when we train a model for a specific object, then this model can only be tested for images which similar to the train set. so what can we do with our own trained model? all i know is that we can use it to extract mesh model.

My goal is to build a 3D model with some 2D images, i don't konw whether this repo can achieve it  or not. The biggest problem is how to use depth map to add color to the extract mesh model. Can you show some guideline for me? I'll be very appreciate.

**Comment by kwea123** [comment]
I wrote code to generate **colored** mesh in [my implementation](https://github.com/kwea123/nerf_pl/blob/master/README_mesh.md), will add a video explanation these days.

**Comment by SpongeGirl** [comment]
Thanks very much for your hard work, this will help me a lot. The result looks good, hope to see your explanation soon.


On 5/2/2020 17:10，kwea123<notifications@github.com> wrote：

I wrote code to generate colored mesh in my implementation, will add a video explanation these days.

**Comment by bmild** [comment]
> I wrote code to generate **colored** mesh in [my implementation](https://github.com/kwea123/nerf_pl/blob/master/README_mesh.md), will add a video explanation these days.

@kwea123 This is cool! One additional idea you could try for getting colors is to treat the vertex normals of the extracted mesh as viewing directions and pass the vertices and normals together back through the NeRF model to get RGB colors out.

**Comment by kwea123** [comment]
@bmild Thanks! It's actually a good idea that I didn't think of! I will give it a try.

**Comment by kwea123** [comment]
@bmild I implemented your method and here's the comparison with mine:
left: yours (using vertex normal) right: mine (using color fusion from input images)
<p>
<img src="https://user-images.githubusercontent.com/11364490/80965584-bcd62c00-8e4d-11ea-85cc-51be13d8beeb.png" width=300>
<img src="https://user-images.githubusercontent.com/11364490/80965588-be075900-8e4d-11ea-8a43-274f4afa48e1.png" width=300>
</p>
<p>
<img src="https://user-images.githubusercontent.com/11364490/80965695-f6a73280-8e4d-11ea-8900-d289fa1aee31.png" width=300>
<img src="https://user-images.githubusercontent.com/11364490/80965696-f73fc900-8e4d-11ea-9af0-c82fa5b7a35e.png" width=300>
</p>

Using normal can produce sharper colors, but I think due to large unevenness of the mesh, the normal vectors are rather inaccurate and noisy, which results in noise here and there. On the other hand, my color fusion fuses colors from several inputs, which have different lighting conditions and result in too much smoothed colors.

My idea of color fusion actually came from my previous research on multi-view stereo, where the problem is to fuse many point clouds and photos into one final colored point cloud; but to my knowledge, there is barely any discussion on how to fuse the color, everyone just simply adds the colors together (since in that field what counts is the final point cloud more than the color)..
In my opinion what can be a future research topic is how to extract real color and the color due to lighting (there must be specific terms for these but sorry I don't know), for example the yellow of lego is actually true yellow plus the lighting that sometimes make it brighter or darker, depending on the angle. I'm sure that NeRF must be able to do that (maybe with some modification?), will do some reseach on it!

**Comment by stone100010** [comment]
> I've trained my own nerf model using 80~100 real images successfully, it takes 8 hours for 50000 iters (probably my GPU not so good), so i think it will take four times hours for 20k iters, it's too long.
> 
> And i have no idea about how to use the trained model, because it's not like most general deep learning models. In my opinion, when we train a model for a specific object, then this model can only be tested for images which similar to the train set. so what can we do with our own trained model? all i know is that we can use it to extract mesh model.
> 
> My goal is to build a 3D model with some 2D images, i don't konw whether this repo can achieve it or not. The biggest problem is how to use depth map to add color to the extract mesh model. Can you show some guideline for me? I'll be very appreciate.

I have the same question. I hope to get in touch with you. Please contact me as soon as possible

**Comment by SpongeGirl** [comment]
@stone100010 
Please read the above answers carefully, to extract colored mesh model you can see this implementation [https://github.com/kwea123/nerf_pl](url) .

**Comment by roganelli** [comment]
> @bmild I implemented your method and here's the comparison with mine:
> left: yours (using vertex normal) right: mine (using color fusion from input images)
> 
> <img alt="" width="300" src="https://user-images.githubusercontent.com/11364490/80965584-bcd62c00-8e4d-11ea-85cc-51be13d8beeb.png"> <img alt="" width="300" src="https://user-images.githubusercontent.com/11364490/80965588-be075900-8e4d-11ea-8a43-274f4afa48e1.png">
> 
> <img alt="" width="300" src="https://user-images.githubusercontent.com/11364490/80965695-f6a73280-8e4d-11ea-8900-d289fa1aee31.png"> <img alt="" width="300" src="https://user-images.githubusercontent.com/11364490/80965696-f73fc900-8e4d-11ea-9af0-c82fa5b7a35e.png">
> 
> Using normal can produce sharper colors, but I think due to large unevenness of the mesh, the normal vectors are rather inaccurate and noisy, which results in noise here and there. On the other hand, my color fusion fuses colors from several inputs, which have different lighting conditions and result in oversmoothed colors.
> 
> My idea of color fusion actually came from my previous research on multi-view stereo, where the problem is to fuse many point clouds and photos into one final colored point cloud; but to my knowledge, there is barely any discussion on how to fuse the color, everyone just simply adds the colors together (since in that field what counts is the final point cloud more than the color)..
> In my opinion what can be a future research topic is how to extract real color and the color due to lighting (there must be specific terms for these but sorry I don't know), for example the yellow of lego is actually true yellow plus the lighting that sometimes make it brighter or darker, depending on the angle. I'm sure that NeRF must be able to do that (maybe with some modification?), will do some reseach on it!

I was going to try your texturing approach from imagery but also tried to the suggestion here with no luck. Any tips on how you were able to get the colors using the vertex normals and vertices themselves. I have not been able to get this working quite right.

**Comment by kwea123** [comment]
After constructing the mesh using marching cubes, I use `open3d` to compute vertices normals based on the mesh. Then simply use these normals as the direction vectors (or maybe the opposite since the rays are pointing from camera to object), and pass along with the vertices as xyz vectors. If using his code, replace the `viewdirs=np.zeros_like(flat[i0:i1])` in `extract_mesh.ipynb` cell 3 with the normal vectors.

**Comment by roganelli** [comment]
> After constructing the mesh using marching cubes, I use `open3d` to compute vertices normals based on the mesh. Then simply use these normals as the direction vectors (or maybe the opposite since the rays are pointing from camera to object), and pass along with the vertices as xyz vectors. If using his code, replace the `viewdirs=np.zeros_like(flat[i0:i1])` in `extract_mesh.ipynb` cell 3 with the normal vectors (I didn't try his code, I use my own implementation).

Great! Thanks I will give that a try.

**Comment by NicksonYap** [comment]
@kwea123  Does your implementstion in https://github.com/kwea123/nerf_pl also include the vertex normal method?
I could't seem to find any references to vertex normals in your code / issues

**Comment by kwea123** [comment]
@NicksonYap Since it doesn't produce satisfactory result, I deleted in my code. I can added again for comparison.

**Comment by kwea123** [comment]
I noticed a bug in my previous implementation of vertex normal method. I was only calculating the color from the surface point, which violates the concept of volume rendering...
The "correct" implementation (this is my intuition, maybe other methods are good too) is to define the `rays_d` as the vertex normal then define `rays_o` as `vertices + ray_d * t` where `t` is a parameter to tune. I illustrated this as follows:
![8](https://user-images.githubusercontent.com/11364490/82452176-e0ee6a00-9ae9-11ea-851c-2a36d5726ff1.png)

*  to determine the color of vertex `v`, knowing its normal `n`
*  we must compose (alpha-blend) the colors of a ray segment that covers vertex `v`, which should approximately cover the volume of the whole object as in training (so not too small)
*  therefore, the near bound should be something in the form `v+tn`, and far bound `v-t'n`. Since we know the far bound `far`, we can use `t' = far`, which guarantees the whole object lies in that range

In my experiments, these are what I get using different `t`:
`t=near`
![6](https://user-images.githubusercontent.com/11364490/82452469-43476a80-9aea-11ea-95ab-3074a7533645.png)
`t=2*near`
![7](https://user-images.githubusercontent.com/11364490/82452505-4d696900-9aea-11ea-9999-ad54ca774c3a.png)
it seems `t` is important to cover the real object color. But the method still fails to reconstruct real and smooth colors, which again, I think, due to the noisy vertex normals. On the other hand, it turns out that it performs quite well on `lego` when `t=near`:
![5](https://user-images.githubusercontent.com/11364490/82452594-6eca5500-9aea-11ea-9b34-982f1ab38047.png)
but fails again for `t=2*near`:
![9](https://user-images.githubusercontent.com/11364490/82453966-31ff5d80-9aec-11ea-8103-144655614b14.png)
for example the floor in the red circle, the normal is pointing upwards, if we include too much ray space, the upper yellow excavator bucket is going to be included, resulting in yellow tint on the floor.

I will include the code in my implementation.

**Comment by ynma-hanvo** [comment]
@SpongeGirl   hi, how did you get the poses for a suck a 
a spherically captured 360 scene  ?
