### ISSUE TITLE
NDC near plane definition

### ISSUE THREAD

**Issue by sally-chen** [bmild/nerf#45]
Thanks for sharing the NDC projection derivation in previous issues. I just have a queston regarding the "final trick" you mentioned at the bottom of page 3 where you move the ray's origin to near plane then perform the projection. Why do you use z = -n instead of z = n? It does make sense in equation 20 to plug in -n but what's the physial meaning in this --- is it because the ray is originally in the -z direction?
(When the code uses front-facing llff images, near plane is at 1, but you are in fact pushing the origin to -1 which is required for NDC, but what does the near plane at 1 represent? Or is it the same as -1 but just the definition of direction is different?) 

Thanks in advance!

**Comment by bmild** [comment]
Yes, it's because the camera is looking in the -z direction and all rays are pointing in that hemisphere of directions. Note that when the rays are instantiated [here](https://github.com/bmild/nerf/blob/master/run_nerf_helpers.py#L127) they use -1 for the z component. And the line [here](https://github.com/bmild/nerf/blob/master/run_nerf_helpers.py#L161) in the NDC function solves for the `t` value such that 
`o + t * d = -near`. In general we store scene bounds (near/far) as positive values and then account for this negative convention in the code, either by scaling a negative z component or by explicitly accounting for it by negating the value, as in these two places.

**Comment by sally-chen** [comment]
Thanks for your reply, I got it now! Also, if I understood correctly the projection matrix in equation 1 is the mapping of a point in camera coordinate to NDC, based on how objects appear in the camera which performs perspective projection of the object to near/far plane then maps to NDC. But in the code ray_o and ray_d are both in world coordinates, and we are specifically transforming the camera centre. Does this matrix still apply in the same way despite the world coordinates?

**Comment by bmild** [comment]
Yes, good point -- this code assumes that if you're using NDC your input poses have been remapped in the data loader to be in the camera coordinate frame of some centered "average" camera pose, which is exactly what happens [here](https://github.com/bmild/nerf/blob/master/load_llff.py#L262). We need rays from different cameras to live in the same global NDC space or they won't intersect at the same points they would in real space, hence the assumed use of a single shared average camera (which has the identity matrix as its pose here).

**Comment by sally-chen** [comment]
Thank you so much for your reply, I'm closing this issue.
