### ISSUE TITLE
Quadrature formula

### ISSUE THREAD

**Issue by denkorzh** [bmild/nerf#7]
First, thank you for sharing the code!
Could you please explain the derivation of the quadrature formula (3) from the paper?
Why  does the term equal `T_i * c_i * (1 - exp(- sigma_i * delta_i))` instead of `T_i * c_i * sigma_i * delta_i`?

**Comment by 99991** [comment]
Also thanks for the code, the results are amazing!

Now about the equation: I don't understand it either, but for small `x`, it holds that `x ≈ 1 - exp(-x)`:

![difference](https://user-images.githubusercontent.com/18725165/77438158-c481ca00-6de5-11ea-9584-a2041320ea10.png)

The Taylor expansion looks like this:

```1 - exp(-x) = x - x^2/2 + x^3/6 + ...```

So the difference is very small:

```1 - exp(- sigma_i * delta_i) ≈ sigma_i * delta_i + O(sigma_i^2 * delta_i^2)```.

**Comment by bmild** [comment]
There's a nice derivation in section 2.3 of [Local and Global Illumination in the Volume
Rendering Integral, Max and Chen 1998](http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.402.6355&rep=rep1&type=pdf).

As they mention, this is a more accurate approximation of the integral for a setting where we treat sigma as constant along intervals of the ray, since it accounts for the earlier part of the segment slightly occluding the later part. (In fact, this version gives the exact answer for a volume where the piecewise constant assumption is actually true.)

**Comment by denkorzh** [comment]
Thanks!
