### ISSUE TITLE
Rendering script for synthetic data

### ISSUE THREAD

**Issue by handsomejac** [bmild/nerf#9]
Hello,
Keep up the great work on this repo!

I wanted to build this for my own obj file in blender, similar to how you have done for the tractor.
I have been trying to use this (https://github.com/panmari/stanford-shapenet-renderer) and I am not sure how to make the transforms.json files.
Would you kindly share the rendering script with the transforms.json files generation ?

**Comment by tancik** [comment]
I'm attaching the rendering script for reference. Because blender scripts are very dependent on the 
.blend file setup we do not plan to include this script in the main repo. 

A few hints when using the script:
+ Only have 1 camera in your scene
+ Place model at origin
+ Set DEBUG=True and run a few times to see where the camera is placed
+ Scale object so that it is visible in the camera view for each debug run

[360_view.py.zip](https://github.com/bmild/nerf/files/4388403/360_view.py.zip)
